#pragma once

typedef enum {
  PROP_FREQ_MAX = 1,
  PROP_SUM_START_IDX,
  PROP_AMP_POW_BASE,
  PROP_AMP_EXP_IDX_MUL,
  PROP_AMPFREQ_SCALE_IDX_MUL,
  PROP_AMPFREQ_SCALE_OFFSET,
  PROP_AMPFREQ_SCALE_EXP,
  PROP_AMP_BOOST_CENTER,
  PROP_AMP_BOOST_SHARPNESS,
  PROP_AMP_BOOST_EXP,
  PROP_AMP_BOOST_DB,
  PROP_RINGMOD_RATE,
  PROP_RINGMOD_DEPTH,
  PROP_RINGMOD_OT_OFFSET,
  PROP_BEND,
  PROP_VOL,
  N_PROPERTIES_SRATE
} PropsSrate;
